# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170118_1119'),
        ('lender_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='borrowed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='books.Book'),
        ),
    ]
