# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170118_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='some_other_dir'),
        ),
    ]
