# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('checked out', 'Checked Out')], default='available', max_length=20),
        ),
    ]
